[tool.black]
    line-length = 80
    target-version = ['py39', 'py310']
    include = '\.pyi?$'
    preview = true
    exclude = '''
    /(
        \.git
      | \.hg
      | \.mypy_cache
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist

      # The following are specific to Black, you probably don't want those.
      | blib2to3
      | tests/data
    )/
  '''

[tool.mypy]
python_version = "3.9"
show_error_codes = true
warn_return_any = true
disallow_untyped_defs = true
pretty = true
show_column_numbers = true 