name: pre-commit

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          name: [3.7,3.9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
